# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='targetUser',
            field=models.IntegerField(default=0),
        ),
    ]
